
from dataclasses import dataclass, field
from typing import Literal, Optional

from kraken_sockets.schema.responses.base_responses import (
    SnapshotResponse,
    UpdateResponse
)


@dataclass
class Fee:
    asset: str
    qty: float


@dataclass
class Trigger:
    reference: str
    price: float
    price_type: str
    actual_price: float
    peak_price: float
    last_price: float
    status: str
    timestamp: str


@dataclass
class Contingent:
    order_type: str
    trigger_price: float
    trigger_price_type: str
    limit_price: float
    limit_price_type: str


class Execution:
    """
    Represents a single execution report object within an executions channel message.

    Attr:
        **order_id**: *(str)* unique Kraken-generated order identifier.
        **symbol**: *(str)* currency pair e.g. "BTC/USD".
        **side**: *(str)* direction of the order, either buy or sell.
        **order_type**: *(str)* type of order e.g. limit, market, stop-loss, etc.
        **order_qty**: *(float)* client-specified order quantity.
        **order_status**: *(str)* current lifecycle status of the order.
        **exec_type**: *(str)* event type that triggered this execution report.
        **timestamp**: *(str)* RFC3339 timestamp of the event.
        **order_userref**: *(int)* optional numeric client identifier.
        **cl_ord_id**: *(str)* optional client-associated order identifier.
        **limit_price**: *(float)* limit price restriction on the order.
        **avg_price**: *(float)* average fill price across all executions.
        **cum_qty**: *(float)* cumulative executed quantity.
        **cum_cost**: *(float)* cumulative value executed in quote currency.
        **cash_order_qty**: *(float)* order volume denominated in quote currency.
        **exec_id**: *(str)* unique execution identifier, present on trade events only.
        **last_price**: *(float)* fill price of the most recent trade event.
        **last_qty**: *(float)* fill quantity of the most recent trade event.
        **cost**: *(float)* value of this individual execution.
        **trade_id**: *(int)* trade identifier associated with this execution.
        **fees**: *(list)* list of Fee objects containing asset and qty.
        **fee_ccy_pref**: *(str)* preferred fee currency, fcib (base) or fciq (quote).
        **fee_usd_equiv**: *(float)* total fee amount expressed in USD equivalent.
        **triggers**: *(Trigger)* trigger conditions for advanced conditional orders.
        **contingent**: *(Contingent)* secondary order template attached to this order.
        **time_in_force**: *(str)* order duration policy, GTC, GTD, or IOC.
        **effective_time**: *(str)* RFC3339 timestamp when order becomes active.
        **expire_time**: *(str)* RFC3339 timestamp when order expires.
        **post_only**: *(bool)* if True, order must rest on the book and not match immediately.
        **reduce_only**: *(bool)* if True, order may only reduce an existing position.
        **margin**: *(bool)* whether the order is eligible for margin funding.
        **margin_borrow**: *(bool)* whether execution was funded via margin borrow.
        **liquidated**: *(bool)* whether the order was generated by the liquidation engine.
        **liquidity_ind**: *(str)* m for maker or t for taker liquidity.
        **amended**: *(bool)* whether the order has been modified since placement.
        **user**: *(str)* Kraken user identifier, present for master and subaccount orders.
    """
    order_id: str
    symbol: str
    side: Literal["buy", "sell"]
    order_type: Literal[
        "limit",
        "market",
        "iceberg",
        "stop-loss",
        "stop-loss-limit",
        "take-profit",
        "take-profit-limit",
        "trailing-stop",
        "trailing-stop-limit",
        "settle-position"
    ]
    order_qty: float
    order_status: Literal[
        "pending_new",
        "new",
        "partially_filled",
        "filled",
        "canceled",
        "expired"
    ]
    exec_type: Literal[
        "pending_new",
        "new",
        "trade",
        "filled",
        "iceberg_refill",
        "canceled",
        "expired",
        "amended",
        "restated",
        "status"
    ]
    timestamp: str
    order_userref: Optional[int]
    cl_ord_id: Optional[str]
    limit_price: Optional[float]
    avg_price: Optional[float]
    cum_qty: Optional[float]
    cum_cost: Optional[float]
    cash_order_qty: Optional[float]
    exec_id: Optional[str]
    last_price: Optional[float]
    last_qty: Optional[float]
    cost: Optional[float]
    trade_id: Optional[int]
    fees: Optional[list[Fee]]
    fee_ccy_pref: Optional[Literal["fcib", "fciq"]]
    fee_usd_equiv: Optional[float]
    triggers: Optional[Trigger]
    contingent: Optional[Contingent]
    time_in_force: Optional[Literal["GTC", "GTD", "IOC"]]
    effective_time: Optional[str]
    expire_time: Optional[str]
    post_only: Optional[bool]
    reduce_only: Optional[bool]
    margin: Optional[bool]
    margin_borrow: Optional[bool]
    liquidated: Optional[bool]
    liquidity_ind: Optional[Literal["m", "t"]]
    amended: Optional[bool]
    user: Optional[str]

    def __init__(self, data: dict) -> None:
        self.order_id = data["order_id"]
        self.symbol = data["symbol"]
        self.side = data["side"]
        self.order_type = data["order_type"]
        self.order_qty = data["order_qty"]
        self.order_status = data["order_status"]
        self.exec_type = data["exec_type"]
        self.timestamp = data["timestamp"]
        self.order_userref = data.get("order_userref")
        self.cl_ord_id = data.get("cl_ord_id")
        self.limit_price = data.get("limit_price")
        self.avg_price = data.get("avg_price")
        self.cum_qty = data.get("cum_qty")
        self.cum_cost = data.get("cum_cost")
        self.cash_order_qty = data.get("cash_order_qty")
        self.exec_id = data.get("exec_id")
        self.last_price = data.get("last_price")
        self.last_qty = data.get("last_qty")
        self.cost = data.get("cost")
        self.trade_id = data.get("trade_id")
        self.fees = [Fee(f["asset"], f["qty"]) for f in data["fees"]] if data.get("fees") else None
        self.fee_ccy_pref = data.get("fee_ccy_pref")
        self.fee_usd_equiv = data.get("fee_usd_equiv")
        self.triggers = Trigger(
            data["triggers"]["reference"],
            data["triggers"]["price"],
            data["triggers"]["price_type"],
            data["triggers"]["actual_price"],
            data["triggers"]["peak_price"],
            data["triggers"]["last_price"],
            data["triggers"]["status"],
            data["triggers"]["timestamp"]
        ) if data.get("triggers") else None
        self.contingent = Contingent(
            data["contingent"]["order_type"],
            data["contingent"]["trigger_price"],
            data["contingent"]["trigger_price_type"],
            data["contingent"]["limit_price"],
            data["contingent"]["limit_price_type"]
        ) if data.get("contingent") else None
        self.time_in_force = data.get("time_in_force")
        self.effective_time = data.get("effective_time")
        self.expire_time = data.get("expire_time")
        self.post_only = data.get("post_only")
        self.reduce_only = data.get("reduce_only")
        self.margin = data.get("margin")
        self.margin_borrow = data.get("margin_borrow")
        self.liquidated = data.get("liquidated")
        self.liquidity_ind = data.get("liquidity_ind")
        self.amended = data.get("amended")
        self.user = data.get("user")


@dataclass
class Wallet:
    balance: float
    type: str
    id: str


class BalanceAsset:
    """
    Represents a single asset holding within a balances channel snapshot.

    Attr:
        **asset**: *(str)* asset symbol code e.g. "BTC".
        **asset_class**: *(str)* asset class, currently always "currency".
        **balance**: *(float)* total asset amount across all wallet types.
        **wallets**: *(list)* list of Wallet objects breaking the balance down by
            wallet type ('spot' or 'earn') and id ('main', 'flex', 'bonded', etc.).
    """
    asset: str
    asset_class: str
    balance: float
    wallets: list[Wallet]

    def __init__(self, data: dict) -> None:
        self.asset = data["asset"]
        self.asset_class = data.get("asset_class", "currency")
        self.balance = data["balance"]
        self.wallets = [
            Wallet(w.get("balance"), w.get("type"), w.get("id"))
            for w in data.get("wallets", [])
        ]


class LedgerEntry:
    """
    Represents a single account ledger transaction within a balances channel update.

    Attr:
        **asset**: *(str)* asset symbol code e.g. "BTC".
        **asset_class**: *(str)* asset class, currently always "currency".
        **amount**: *(float)* asset change quantity in this event.
        **balance**: *(float)* total asset held after the transaction.
        **fee**: *(float)* fee amount for the transaction.
        **ledger_id**: *(str)* unique account ledger entry identifier.
        **ref_id**: *(str)* context-specific reference id, e.g. trade id for trades.
        **timestamp**: *(str)* RFC3339 timestamp of the transaction.
        **type**: *(str)* broad event category e.g. trade, deposit, withdrawal, transfer.
        **subtype**: *(str)* specific event subtype e.g. spotfromfutures.
        **category**: *(str)* event categorization e.g. trade, margin-trade, conversion.
        **wallet_type**: *(str)* wallet type, 'spot' or 'earn'.
        **wallet_id**: *(str)* wallet identifier e.g. 'main', 'flex'.
        **user**: *(str)* Kraken user identifier, present only when users='all' was requested.
    """
    asset: str
    asset_class: str
    amount: float
    balance: float
    fee: Optional[float]
    ledger_id: str
    ref_id: Optional[str]
    timestamp: str
    type: str
    subtype: Optional[str]
    category: Optional[str]
    wallet_type: Optional[str]
    wallet_id: Optional[str]
    user: Optional[str]

    def __init__(self, data: dict) -> None:
        self.asset = data["asset"]
        self.asset_class = data.get("asset_class", "currency")
        self.amount = data["amount"]
        self.balance = data["balance"]
        self.fee = data.get("fee")
        self.ledger_id = data.get("ledger_id", "")
        self.ref_id = data.get("ref_id")
        self.timestamp = data.get("timestamp", "")
        self.type = data.get("type", "")
        self.subtype = data.get("subtype")
        self.category = data.get("category")
        self.wallet_type = data.get("wallet_type")
        self.wallet_id = data.get("wallet_id")
        self.user = data.get("user")


class BalancesSnapshotResponse(SnapshotResponse):
    """
    Snapshot of all asset balances on the account sent after successfully
    subscribing to the 'balances' channel.

    Docs @ https://docs.kraken.com/api/docs/websocket-v2/balances

    Arg:
        **message**: *(dict)* dict containing response data.

    Attr:
        **balances**: *(list)* list of BalanceAsset objects, one per asset held,
            each with a per-wallet breakdown.
        **sequence**: *(int)* subscription message sequence number used to detect gaps.
    """
    balances: list[BalanceAsset]
    sequence: int

    def __init__(self, message: dict) -> None:
        self.balances = [BalanceAsset(item) for item in message["data"]]
        self.sequence = message["sequence"]


class BalancesUpdateResponse(UpdateResponse):
    """
    Real-time account ledger transactions streamed on the 'balances' channel,
    e.g. trades settling, deposits, withdrawals, and transfers.

    Docs @ https://docs.kraken.com/api/docs/websocket-v2/balances

    Arg:
        **message**: *(dict)* dict containing response data.

    Attr:
        **ledger_entries**: *(list)* list of LedgerEntry objects for this event.
        **sequence**: *(int)* subscription message sequence number used to detect gaps.
    """
    ledger_entries: list[LedgerEntry]
    sequence: int

    def __init__(self, message: dict) -> None:
        self.ledger_entries = [LedgerEntry(item) for item in message["data"]]
        self.sequence = message["sequence"]


class ExecutionsSnapshotResponse(SnapshotResponse):
    """
    Snapshot of open orders and recent execution history sent after successfully
    subscribing to the 'executions' channel.

    Docs @ https://docs.kraken.com/api/docs/websocket-v2/executions

    Arg:
        **message**: *(dict)* dict containing response data.

    Attr:
        **executions**: *(list)* list of Execution objects representing current open orders
            and recent fills at the time of subscription.
        **sequence**: *(int)* subscription message sequence number used to detect gaps.
    """
    executions: list[Execution]
    sequence: int

    def __init__(self, message: dict) -> None:
        self.executions = [Execution(item) for item in message["data"]]
        self.sequence = message["sequence"]


class ExecutionsUpdateResponse(UpdateResponse):
    """
    Real-time execution report streamed on order lifecycle events such as new orders,
    fills, cancellations, and amendments.

    Docs @ https://docs.kraken.com/api/docs/websocket-v2/executions

    Arg:
        **message**: *(dict)* dict containing response data.

    Attr:
        **executions**: *(list)* list of Execution objects for this update event.
            The exec_type field on each indicates what triggered the report.
        **sequence**: *(int)* subscription message sequence number used to detect gaps.
    """
    executions: list[Execution]
    sequence: int

    def __init__(self, message: dict) -> None:
        self.executions = [Execution(item) for item in message["data"]]
        self.sequence = message["sequence"]
